server:
  port: 8888
mybatis:
  mapper-locations: classpath:mappers/*xml
spring:
  profiles:
    active: product
    #    active: product
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
